language: python
sudo: required
python:
  - "2.7"
  - "3.4"

install:
 - sudo apt-get install libsodium13
 - python setup.py install

script:
 - python -m unittest discover --start-directory test

notifications:
  email: false
