language: python
sudo: required
python:
  - "3.4"
  - "3.3"
  - "2.7"

install:
 - sudo apt-get install libsodium
 - python setup.py install

script:
 - python -m unittest discover --start-directory test

notifications:
  email: false
